services:
  app: # Name of the service (could be 'app' or 'web' too)
    container_name: firstcontainer # Explicitly names the container
    #! UPDATE TAG NAME BEFORE PUSHING CHANGES /firstimage:Vx
    image: docker.io/${DOCKER_HUB_USERNAME}/firstimage:V3.0

    build:
      context: . # Build context - where Docker looks for Dockerfile
      target: base # Specifically targets the development stage in multi-stage Dockerfile
      secrets:
        - shopify_domain
        - shopify_token

    working_dir: /app

    restart: always # Automatically restart if container stops

    command: npm run dev # Overrides default CMD, runs development server

    env_file:
      - .env.local

    environment:
      - NODE_ENV=development # Sets environment to development mode
      # Windows-specific polling for file changes
      #- WATCHPACK_POLLING=true

    volumes:
      - .:/app # Mount current directory to /app in container
      # - /app/node_modules # Preserve node_modules volume
      - /app/.next # Preserve Next.js build cache

    ports:
      - 3000:3000 # Map container port to host port

secrets:
  shopify_domain:
    file: ./secrets/shopify_domain.txt
  shopify_token:
    file: ./secrets/shopify_token.txt