services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      secrets: |
        "shopify_domain=${{ secrets.SHOPIFY_STORE_DOMAIN }}"
        "shopify_token=${{ secrets.SHOPIFY_STOREFRONT_ACCESS_TOKEN }}"

    ports:
      - "3000:3000"
    environment:
      - SHOPIFY_STORE_DOMAIN=${SHOPIFY_STORE_DOMAIN}
      - SHOPIFY_STOREFRONT_ACCESS_TOKEN=${SHOPIFY_STOREFRONT_ACCESS_TOKEN}
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g # Prevents insufficient memory crash
    ports:
      - "4444:4444"
