name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: login to docker hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:latest
          # replace "latest" with stable version if needed

      - name: build and push docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          #! UPDATE TAG NAME BEFORE PUSHING CHANGES /firstimage:Vx
          tags: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/firstimage:V3.0

          #! Using Docker Build Secrets:
          build-args: |
            DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}

  # testing with selenium

  test:
    runs-on: ubuntu-latest
    needs: build # Ensures tests run after the build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file for CI
        run: |
          echo "SHOPIFY_STORE_DOMAIN=${{ secrets.SHOPIFY_STORE_DOMAIN }}" > .env.local 
          echo "SHOPIFY_STOREFRONT_ACCESS_TOKEN=${{ secrets.SHOPIFY_STOREFRONT_ACCESS_TOKEN }}" >> .env.local
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" >> .env.local
          echo "TEST=test" >> .env.local
          cat .env.local > .env

      - name: Debug environment variables & secrets
        run: |
          echo "SHOPIFY_STORE_DOMAIN exists: ${{ secrets.SHOPIFY_STORE_DOMAIN != '' }}"
          echo "SHOPIFY_STOREFRONT_ACCESS_TOKEN exists: ${{ secrets.SHOPIFY_STOREFRONT_ACCESS_TOKEN != '' }}"
          echo "Checking .env.local file:"
          cat .env.local
          echo "Checking .env files:"
          cat .env

        # Show file without exposing secrets

      - name: Start Selenium + Build service
        env:
          SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
          SHOPIFY_STOREFRONT_ACCESS_TOKEN: ${{ secrets.SHOPIFY_STOREFRONT_ACCESS_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          TEST: test
        run: |
          echo "Domain length: ${#SHOPIFY_STORE_DOMAIN}" > env_check.txt
          echo "Token length: ${#SHOPIFY_STOREFRONT_ACCESS_TOKEN}" >> env_check.txt
          cat env_check.txt
          docker compose -f docker-compose.test.yml --env-file .env up -d

      - name: Build and run tests
        env:
          SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
          SHOPIFY_STOREFRONT_ACCESS_TOKEN: ${{ secrets.SHOPIFY_STOREFRONT_ACCESS_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          TEST: test
        run: |
          docker build -t web-test -f Dockerfile.test .
          docker run --rm --network=host \
            web-test

      - name: Stop Selenium services
        if: always()
        run: docker compose down

  # buildx doesn't store under local docker daemon image storage
